In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('Bank.csv')

In [5]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [6]:
df.loc[df.age>50]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
6,56,management,married,tertiary,no,830,yes,yes,unknown,6,may,1201,1,-1,0,unknown,yes
7,60,retired,divorced,secondary,no,545,yes,no,unknown,6,may,1030,1,-1,0,unknown,yes
31,60,technician,married,primary,no,65,yes,no,unknown,9,may,1028,2,-1,0,unknown,yes
40,60,blue-collar,married,primary,no,1262,yes,yes,unknown,13,may,1015,1,-1,0,unknown,yes
44,52,management,married,unknown,no,2240,yes,no,unknown,13,may,845,1,-1,0,unknown,yes
47,52,housemaid,married,secondary,no,3923,yes,no,unknown,14,may,942,3,-1,0,unknown,yes
48,53,technician,divorced,primary,no,1443,yes,no,unknown,14,may,476,1,-1,0,unknown,yes
52,59,retired,married,secondary,no,1521,yes,yes,unknown,14,may,1125,2,-1,0,unknown,yes
57,60,retired,married,primary,no,1542,yes,no,unknown,14,may,930,1,-1,0,unknown,yes
59,57,technician,married,tertiary,no,-1,no,no,unknown,14,may,850,2,-1,0,unknown,yes
60,51,blue-collar,married,secondary,no,7180,yes,no,unknown,14,may,927,1,-1,0,unknown,yes
63,52,blue-collar,divorced,primary,no,-191,yes,no,unknown,15,may,755,1,-1,0,unknown,yes
64,59,blue-collar,married,primary,no,320,yes,no,unknown,15,may,695,1,-1,0,unknown,yes
70,60,services,single,primary,no,313,yes,no,unknown,15,may,920,2,-1,0,unknown,yes
86,54,management,single,tertiary,no,4393,yes,no,unknown,16,may,1297,3,-1,0,unknown,yes
145,59,services,married,secondary,no,-22,yes,no,unknown,26,may,748,3,-1,0,unknown,yes
148,59,retired,single,secondary,no,351,yes,no,unknown,27,may,1063,5,-1,0,unknown,yes
163,51,entrepreneur,married,unknown,no,606,yes,no,unknown,28,may,560,9,-1,0,unknown,yes
166,56,blue-collar,married,secondary,no,249,yes,no,unknown,29,may,791,2,-1,0,unknown,yes
168,60,blue-collar,divorced,secondary,no,0,yes,no,unknown,29,may,1207,1,-1,0,unknown,yes
169,56,technician,married,secondary,no,589,yes,no,unknown,29,may,535,2,-1,0,unknown,yes
192,53,blue-collar,divorced,primary,no,2656,yes,no,unknown,30,may,1980,2,-1,0,unknown,yes
198,53,entrepreneur,single,secondary,no,62,yes,no,unknown,30,may,1044,5,-1,0,unknown,yes
238,59,retired,divorced,primary,no,-88,yes,no,unknown,5,jun,910,2,-1,0,unknown,yes
240,58,entrepreneur,married,tertiary,no,853,no,no,unknown,5,jun,1149,2,-1,0,unknown,yes
246,53,housemaid,married,primary,no,104,no,yes,unknown,5,jun,701,1,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10984,55,blue-collar,married,primary,no,3297,yes,yes,telephone,30,apr,96,1,-1,0,unknown,no
10987,58,blue-collar,married,secondary,no,381,no,no,cellular,11,nov,79,4,-1,0,unknown,no
10995,53,self-employed,married,primary,no,4576,no,no,telephone,30,jul,82,2,-1,0,unknown,no
10996,53,technician,divorced,unknown,no,629,yes,no,cellular,8,may,298,1,-1,0,unknown,no
11004,55,blue-collar,married,primary,no,-79,no,yes,unknown,27,jun,293,3,-1,0,unknown,no
11008,56,services,married,unknown,no,616,no,no,unknown,18,jun,1812,1,-1,0,unknown,no
11010,55,unemployed,married,primary,no,8585,no,no,telephone,28,jan,201,2,-1,0,unknown,no
11012,57,admin.,married,secondary,no,808,no,no,cellular,14,jul,417,3,-1,0,unknown,no
11036,54,housemaid,divorced,tertiary,no,9,no,yes,cellular,29,jul,136,3,-1,0,unknown,no
11052,54,housemaid,married,primary,no,212,no,no,cellular,12,aug,81,4,-1,0,unknown,no
11060,58,housemaid,married,primary,no,435,yes,no,telephone,28,jul,122,6,-1,0,unknown,no
11064,55,retired,married,tertiary,no,2929,no,no,unknown,16,jun,556,3,-1,0,unknown,no
11076,52,services,married,secondary,no,820,yes,no,cellular,2,feb,135,2,-1,0,unknown,no
11077,54,retired,divorced,tertiary,no,6102,yes,yes,unknown,21,may,86,6,-1,0,unknown,no
11079,60,retired,married,tertiary,no,0,no,no,cellular,25,aug,101,3,-1,0,unknown,no
11085,60,technician,married,primary,no,4243,yes,no,cellular,4,feb,387,1,251,1,failure,no
11094,57,unemployed,married,primary,no,2743,no,no,cellular,29,jan,89,1,-1,0,unknown,no
11097,56,management,married,primary,no,21,no,no,cellular,7,jul,118,1,-1,0,unknown,no
11101,54,blue-collar,married,primary,no,6242,yes,no,cellular,7,may,162,1,-1,0,unknown,no
11103,51,management,married,primary,no,98,yes,no,unknown,7,may,114,2,-1,0,unknown,no
11105,54,entrepreneur,married,tertiary,no,0,no,no,cellular,30,jul,250,5,-1,0,unknown,no
11107,54,admin.,married,primary,no,0,no,no,cellular,30,jul,255,2,-1,0,unknown,no
11117,54,management,married,tertiary,no,184,no,no,cellular,6,feb,13,6,-1,0,unknown,no
11131,55,technician,married,secondary,no,276,yes,no,unknown,12,may,486,1,-1,0,unknown,no
11134,58,self-employed,married,tertiary,no,2596,no,no,telephone,18,nov,15,2,-1,0,unknown,no
11140,55,services,divorced,secondary,no,2166,yes,no,unknown,28,may,23,17,-1,0,unknown,no
11142,52,admin.,divorced,secondary,no,48,no,yes,cellular,17,nov,591,1,-1,0,unknown,no
11144,60,retired,married,secondary,no,0,yes,no,unknown,15,may,229,1,-1,0,unknown,no
11145,60,retired,divorced,tertiary,no,-134,no,no,cellular,12,may,243,1,271,4,failure,no
11154,52,technician,married,tertiary,no,523,yes,yes,cellular,8,jul,113,1,-1,0,unknown,no

In [7]:
df = df.drop('duration', axis=1)

In [8]:
print('Shape of dataframe:', df.shape)
df.head()

Shape of dataframe: (11162, 16)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,2,-1,0,unknown,yes

In [9]:
df['deposit'].value_counts()

no     5873
yes    5289
Name: deposit, dtype: int64

In [10]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
df_ready = df.copy()

In [14]:
scaler = StandardScaler()
num_cols = ['age', 'balance', 'day', 'campaign', 'pdays', 'previous']
df_ready[num_cols] = scaler.fit_transform(df_ready[num_cols])

In [15]:
df_ready.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,campaign,pdays,previous,poutcome,deposit
0,1.491505,admin.,married,secondary,no,0.252525,yes,no,unknown,-1.265746,may,-0.554168,-0.481184,-0.36326,unknown,yes
1,1.239676,admin.,married,secondary,no,-0.459974,no,no,unknown,-1.265746,may,-0.554168,-0.481184,-0.36326,unknown,yes
2,-0.019470,technician,married,secondary,no,-0.080160,yes,no,unknown,-1.265746,may,-0.554168,-0.481184,-0.36326,unknown,yes
3,1.155733,services,married,secondary,no,0.293762,yes,no,unknown,-1.265746,may,-0.554168,-0.481184,-0.36326,unknown,yes
4,1.071790,admin.,married,tertiary,no,-0.416876,no,no,unknown,-1.265746,may,-0.186785,-0.481184,-0.36326,unknown,yes

In [16]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
cat_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

In [17]:
df_encoded = pd.DataFrame(encoder.fit_transform(df_ready[cat_cols]))
df_encoded.columns = encoder.get_feature_names(cat_cols)

In [18]:
df_ready = df_ready.drop(cat_cols ,axis=1)
df_ready = pd.concat([df_encoded, df_ready], axis=1)

In [20]:
df_ready['deposit'] = df_ready['deposit'].apply(lambda x: 1 if x == 'yes' else 0)
print('Shape of dataframe:', df_ready.shape)
df_ready.head()

Shape of dataframe: (11162, 51)

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,poutcome_other,poutcome_success,poutcome_unknown,age,balance,day,campaign,pdays,previous,deposit
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.491505,0.252525,-1.265746,-0.554168,-0.481184,-0.36326,1
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.239676,-0.459974,-1.265746,-0.554168,-0.481184,-0.36326,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,-0.019470,-0.080160,-1.265746,-0.554168,-0.481184,-0.36326,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.155733,0.293762,-1.265746,-0.554168,-0.481184,-0.36326,1
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.071790,-0.416876,-1.265746,-0.186785,-0.481184,-0.36326,1

In [22]:
feature = df_ready.drop('deposit', axis=1)

In [23]:
feature

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown,age,balance,day,campaign,pdays,previous
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.491505,0.252525,-1.265746,-0.554168,-0.481184,-0.363260
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.239676,-0.459974,-1.265746,-0.554168,-0.481184,-0.363260
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,-0.019470,-0.080160,-1.265746,-0.554168,-0.481184,-0.363260
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.155733,0.293762,-1.265746,-0.554168,-0.481184,-0.363260
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.071790,-0.416876,-1.265746,-0.186785,-0.481184,-0.363260
5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.064473,-0.473926,-1.265746,-0.186785,-0.481184,-0.363260
6,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.239676,-0.216583,-1.146986,-0.554168,-0.481184,-0.363260
7,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.575448,-0.304948,-1.146986,-0.554168,-0.481184,-0.363260
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,-0.355243,-0.473616,-1.146986,-0.554168,-0.481184,-0.363260
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-1.110730,1.104237,-1.146986,0.180598,-0.481184,-0.363260
10,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.271300,-0.442921,-1.028226,-0.554168,-0.481184,-0.363260
11,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.942844,-0.378120,-1.028226,-0.186785,-0.481184,-0.363260
12,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-1.026787,-0.412226,-1.028226,0.547981,-0.481184,-0.363260
13,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.400245,-0.331302,-1.028226,-0.186785,-0.481184,-0.363260
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,-0.858901,-0.255960,-0.909466,-0.186785,-0.481184,-0.363260
15,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.523129,0.715742,-0.909466,-0.554168,-0.481184,-0.363260
16,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.774958,-0.284484,-0.909466,0.180598,-0.481184,-0.363260
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.652074,-0.476406,-0.909466,-0.554168,-0.481184,-0.363260
18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.019470,-0.456873,-0.909466,-0.186785,-0.481184,-0.363260
19,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.652074,-0.421837,-0.909466,-0.554168,-0.481184,-0.363260
20,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-1.110730,-0.230535,-0.909466,-0.186785,-0.481184,-0.363260
21,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.148416,0.166951,-0.909466,-0.554168,-0.481184,-0.363260
22,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.148416,-0.353626,-0.909466,-0.186785,-0.481184,-0.363260
23,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.148416,-0.533456,-0.909466,-0.186785,-0.481184,-0.363260
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.355243,-0.355796,-0.909466,-0.186785,-0.481184,-0.363260
25,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.523129,-0.461524,-0.790707,0.547981,-0.481184,-0.363260
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,-0.858901,-0.467105,-0.790707,0.180598,-0.481184,-0.363260
27,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.148416,-0.472996,-0.790707,0.180598,-0.481184,-0.363260
28,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.858901,-0.378740,-0.790707,-0.554168,-0.481184,-0.363260
29,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-1.110730,-0.238597,-0.790707,-0.554168,-0.481184,-0.363260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11132,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.774958,-0.574693,0.634410,-0.554168,-0.481184,-0.363260
11133,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,-0.355243,0.020296,0.159371,-0.554168,1.918741,1.818332
11134,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.407562,0.330968,0.278131,-0.186785,-0.481184,-0.363260
11135,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.439186,-0.438270,-1.146986,-0.554168,-0.481184,-0.363260
11136,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.858901,-0.473926,-0.909466,-0.554168,-0.481184,-0.363260
11137,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.652074,-0.397343,-0.078148,-0.186785,-0.481184,-0.363260
11138,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,-0.774958,-0.401064,1.465728,1.282747,-0.481184,-0.363260
11139,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.942844,0.330038,1.346969,1.650129,-0.481184,-0.363260
11140,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.155733,0.197646,1.465728,5.323959,-0.481184,-0.363260
11141,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.774958,-0.433619,-1.146986,-0.186785,-0.481184,-0.363260
11142,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.903903,-0.459043,0.159371,-0.554168,-0.481184,-0.363260
11143,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.271300,-0.415326,0.634410,-0.186785,-0.481184,-0.363260
11144,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.575448,-0.473926,-0.078148,-0.554168,-0.481184,-0.363260
11145,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.575448,-0.515473,-0.434427,-0.554168,2.019887,1.382014
11146,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.942844,-0.466795,-1.384505,-0.186785,-0.481184,-0.363260
11147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.232359,-0.473926,0.634410,0.547981,-0.481184,-0.363260
11148,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.774958,-0.473616,-0.909466,-0.554168,-0.481184,-0.363260
11149,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.400245,0.554515,0.396891,-0.186785,-0.481184,-0.363260
11150,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.607072,-0.363858,0.634410,0.180598,-0.481184,-0.363260
11151,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.103413,-0.189609,0.515650,-0.554168,-0.481184,-0.363260
11152,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.607072,-0.353006,-0.078148,0.180598,-0.481184,-0.363260
11153,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.148416,-0.463074,-0.790707,-0.554168,-0.481184,-0.363260
11154,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.903903,-0.311769,-0.909466,-0.554168,-0.481184,-0.363260
11155,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,-0.523129,-0.449122,0.634410,-0.186785,1.109571,0.509377
11156,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.607072,-0.496250,-1.028226,0.915364,-0.481184,-0.363260
11157,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.691015,-0.473616,0.515650,-0.554168,-0.481184,-0.363260
11158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-0.187357,-0.246658,0.040612,0.547981,-0.481184,-0.363260
11159,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,-0.774958,-0.464934,0.396891,-0.186785,-0.481184,-0.363260
11160,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.148416,-0.473926,-0.909466,-0.186785,1.109571,1.818332
11161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,-0.607072,-0.473926,-0.790707,-0.554168,-0.481184,-0.363260

In [24]:
target = df_ready['deposit']

In [25]:
target

0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
11132    0
11133    0
11134    0
11135    0
11136    0
11137    0
11138    0
11139    0
11140    0
11141    0
11142    0
11143    0
11144    0
11145    0
11146    0
11147    0
11148    0
11149    0
11150    0
11151    0
11152    0
11153    0
11154    0
11155    0
11156    0
11157    0
11158    0
11159    0
11160    0
11161    0
Name: deposit, Length: 11162, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test=train_test_split(feature,target,test_size=0.2)

In [29]:
print(x_train.shape)

(8929, 50)

In [30]:
print(x_test.shape)

(2233, 50)

In [31]:
print(y_train.shape)

(8929,)

In [32]:
print(y_test.shape)

(2233,)